INFO - 2023-10-08 07:19:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:19:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:23:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:23:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:26:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:26:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:26:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:27:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:32:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:34:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:34:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:34:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:35:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:38:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:38:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:38:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:38:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 07:38:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:10:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:10:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:11:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:11:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:15:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:17:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:34:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:35:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:38:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:40:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:51:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 08:54:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 09:06:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 09:07:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 10:59:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:14:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:14:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:29:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:29:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:30:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:30:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id21138333_admin'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'id21138333_admi...', Object(SensitiveParameterValue), 'id21138333_madh...', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:30:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:34:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:34:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:34:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'id21138333_admin'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'id21138333_admi...', Object(SensitiveParameterValue), 'id21138333_madh...', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:34:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:35:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:35:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:35:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:35:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:35:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:35:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:35:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:35:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:36:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:36:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:36:58 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:36:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:39:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:39:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:39:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:39:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:39:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:39:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:39:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 11:44:18 --> Undefined property: Config\App::$baseURL
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 SYSTEMPATH\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: Config\\App::$baseURL', 'C:\\xampp\\htdocs\\self_drive\\system\\HTTP\\SiteURI.php', 193)
 2 SYSTEMPATH\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 3 SYSTEMPATH\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', null)
 5 SYSTEMPATH\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
 6 SYSTEMPATH\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 8 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 9 SYSTEMPATH\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
10 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
11 SYSTEMPATH\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', [])
12 SYSTEMPATH\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 11:44:18 --> Uncaught ErrorException: Undefined property: Config\App::$baseURL in C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php:193
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(519): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\self_drive\system\Debug\Exceptions.php(135): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#18 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: Config\App::$baseURL
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\self_drive\system\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-08 11:44:22 --> Undefined property: Config\App::$baseURL
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 SYSTEMPATH\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: Config\\App::$baseURL', 'C:\\xampp\\htdocs\\self_drive\\system\\HTTP\\SiteURI.php', 193)
 2 SYSTEMPATH\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 3 SYSTEMPATH\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', null)
 5 SYSTEMPATH\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
 6 SYSTEMPATH\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 8 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 9 SYSTEMPATH\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
10 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
11 SYSTEMPATH\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', [])
12 SYSTEMPATH\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 11:44:22 --> Uncaught ErrorException: Undefined property: Config\App::$baseURL in C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php:193
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(519): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\self_drive\system\Debug\Exceptions.php(135): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#18 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: Config\App::$baseURL
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\self_drive\system\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-08 11:44:23 --> Undefined property: Config\App::$baseURL
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 SYSTEMPATH\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: Config\\App::$baseURL', 'C:\\xampp\\htdocs\\self_drive\\system\\HTTP\\SiteURI.php', 193)
 2 SYSTEMPATH\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 3 SYSTEMPATH\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', null)
 5 SYSTEMPATH\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
 6 SYSTEMPATH\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 8 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 9 SYSTEMPATH\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
10 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
11 SYSTEMPATH\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', [])
12 SYSTEMPATH\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 11:44:23 --> Uncaught ErrorException: Undefined property: Config\App::$baseURL in C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php:193
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(519): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\self_drive\system\Debug\Exceptions.php(135): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#18 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: Config\App::$baseURL
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\self_drive\system\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-08 11:44:24 --> Undefined property: Config\App::$baseURL
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 SYSTEMPATH\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: Config\\App::$baseURL', 'C:\\xampp\\htdocs\\self_drive\\system\\HTTP\\SiteURI.php', 193)
 2 SYSTEMPATH\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 3 SYSTEMPATH\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', null)
 5 SYSTEMPATH\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
 6 SYSTEMPATH\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 7 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 8 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 9 SYSTEMPATH\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
10 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
11 SYSTEMPATH\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', [])
12 SYSTEMPATH\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 11:44:24 --> Uncaught ErrorException: Undefined property: Config\App::$baseURL in C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php:193
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(519): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\self_drive\system\Debug\Exceptions.php(135): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#18 {main}
  thrown
【Previous Exception】
ErrorException
Undefined property: Config\App::$baseURL
#0 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(193): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193)
#1 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#2 C:\xampp\htdocs\self_drive\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#3 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), 'login', NULL)
#4 C:\xampp\htdocs\self_drive\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('login')
#5 C:\xampp\htdocs\self_drive\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#6 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#7 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#8 C:\xampp\htdocs\self_drive\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#9 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#10 C:\xampp\htdocs\self_drive\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#11 C:\xampp\htdocs\self_drive\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#12 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\self_drive\system\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\self_drive\system\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\self_drive\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 193.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-10-08 11:44:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:44:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:44:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:44:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:45:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:45:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:45:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:45:08 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:47:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:47:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:47:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'selfdrive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:47:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:48:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:48:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:48:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:48:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:48:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:48:53 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:48:53 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:52:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:53:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-10-08 11:53:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'self_drive', 3306, '', 0)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\self_drive\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\self_drive\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\self_drive\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\self_drive\app\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
#5 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#6 C:\xampp\htdocs\self_drive\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\self_drive\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-08 11:53:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `email` = :email:', [...], false)
 3 APPPATH\Controllers\LoginController.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\LoginController->authenticate()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:53:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:53:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:53:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 11:57:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2023-10-08 11:57:33 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 11:59:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2023-10-08 11:59:26 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:00:36 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:15:11 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 12:15:11 --> Undefined variable $result
in APPPATH\Controllers\BookingController.php on line 57.
 1 APPPATH\Controllers\BookingController.php(57): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $result', 'C:\\xampp\\htdocs\\self_drive\\app\\Controllers\\BookingController.php', 57)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\BookingController->booking_insert_data()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BookingController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:15:36 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:16:24 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:16:33 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 12:17:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2023-10-08 12:18:06 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 12:22:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2023-10-08 12:22:39 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:27:24 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 12:27:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2023-10-08 12:27:35 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:29:48 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:30:05 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:30:12 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 12:30:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2023-10-08 12:31:14 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-08 12:31:14 --> Call to undefined method App\Controllers\BookingController::duplicate_data()
in APPPATH\Controllers\BookingController.php on line 44.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\BookingController->booking_insert_data()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BookingController))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:31:49 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$MasterInformationModel is deprecated in APPPATH\Controllers\BookingController.php on line 22.
 1 SYSTEMPATH\CodeIgniter.php(891): App\Controllers\BookingController->__construct()
 2 SYSTEMPATH\CodeIgniter.php(485): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
WARNING - 2023-10-08 12:31:49 --> [DEPRECATED] Creation of dynamic property App\Controllers\BookingController::$db is deprecated in APPPATH\Controllers\BookingController.php on line 68.
 1 APPPATH\Controllers\BookingController.php(44): App\Controllers\BookingController->duplicate_data([...], 'car_booking')
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\BookingController->booking_insert_data()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BookingController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-10-08 13:56:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 13:56:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 13:57:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 13:57:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-08 13:57:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
